-- use this file to map the AP location ids to your locations
-- to reference a location in Pop use @ in the beginning and then path to the section (more info: https://github.com/black-sliver/PopTracker/blob/master/doc/PACKS.md#locations)
-- to reference an item use it's code
-- here are the SM locations as an example: https://github.com/Cyb3RGER/sm_ap_tracker/blob/main/scripts/autotracking/location_mapping.lua
LOCATION_MAPPING = {
   --Sealed Room
    [0xD55C0035] = {"@Sealed Room: Main shaft left fake wall/"},
    --Catacombs
    [0xD55C0037] = {"@Catacomb: Push crate treasure room/"},
    [0xD55C0043] = {"@Catacomb: Fleamen brain room - Lower/"},
    [0xD55C0036] = {"@Catacomb: Fleamen brain room - Upper/"},
    [0xD55C00A8] = {"@Catacomb: Earth Demon dash room/"},
    [0xD55C0038] = {"@Catacomb: Tackle block treasure room/"},
    [0xD55C003A] = {"@Catacomb: Earth Demon bone pit - Lower/"},
    [0xD55C003B] = {"@Catacomb: Earth Demon bone pit - Upper/"},
    [0xD55C0040] = {"@Catacomb: Below right column save room/"},
    [0xD55C0039] = {"@Catacomb: Right column fake wall/"},
    [0xD55C0041] = {"@Catacomb: Right column Spirit room/"},
    [0xD55C003C] = {"@Catacomb: Muddy Mudman platforms room - Lower/"},
    [0xD55C003D] = {"@Catacomb: Muddy Mudman platforms room - Upper/"},
    [0xD55C003E] = {"@Catacomb: Slide space zone/"},
    [0xD55C0042] = {"@Catacomb: Pre-Cerberus lone Skeleton room/"},
    [0xD55C003F] = {"@Catacomb: Pre-Cerberus Hopper treasure room/"},
    [0xD55C00A9] = {"@Catacomb: Behind Cerberus/"},
    [0xD55C0044] = {"@Catacomb: Mummies' fake wall/"},
    --Abyss Staircase
    [0xD55C0047] = {"@Abyss Staircase: Lower fake wall/"},
    [0xD55C0045] = {"@Abyss Staircase: Loopback drop/"},
    [0xD55C0046] = {"@Abyss Staircase: Roc ledge/"},
    [0xD55C0048] = {"@Abyss Staircase: Upper fake wall/"},
    --Audience Room
    [0xD55C0053]  = {"@Audience Room: Skeleton foyer fake wall/"},
    [0xD55C0054] = {"@Audience Room: Main gallery fake wall/"},
    [0xD55C0051]  = {"@Audience Room: Below coyote jump/"},
    [0xD55C004B]  = {"@Audience Room: Push crate gallery/"},
    [0xD55C004A] = {"@Audience Room: Past coyote jump/"},
    [0xD55C0049] = {"@Audience Room: Tackle block gallery/"},
    [0xD55C004D] = {"@Audience Room: Wicked roc chamber - Lower/"},
    [0xD55C004C] = {"@Audience Room: Wicked roc chamber - Upper/"},
    [0xD55C0052] = {"@Audience Room: Upper Devil Tower hallway/"},
    [0xD55C0050] = {"@Audience Room: Right exterior - Lower/"},
    [0xD55C004F] = {"@Audience Room: Right exterior - Upper/"},
    [0xD55C004E] = {"@Audience Room: Right exterior fake wall/"},
    [0xD55C006A] = {"@Audience Room: 100 meter skelly dash hallway/"},
    [0xD55C0055] = {"@Audience Room: Lower Devil Tower hallway fake wall/"},
    [0xD55C00AA] = {"@Audience Room: Behind Necromancer/"},
    [0xD55C0059] = {"@Audience Room: Below Machine Tower roc ledge/"},
    [0xD55C0058] = {"@Audience Room: Below Machine Tower push crate room/"},
    [0xD55C0099] = {"@Audience Room: Roc horse jaguar armory - Left/"},
    [0xD55C009A] = {"@Audience Room: Roc horse jaguar armory - Right/"},
    --Outer Wall
    [0xD55C0097]   = {"@Outer Wall: Left roc ledge/"},
    [0xD55C0098]   = {"@Outer Wall: Right-brained ledge/"},
    [0xD55C009E]   = {"@Outer Wall: Fake Nightmare floor/"},
    --Triumph Hallway
    [0xD55C0057]   = {"@Triumph Hallway: Skeleton slopes fake wall/"},
    [0xD55C0056]   = {"@Triumph Hallway: Entrance Flame Armor climb/"},
    --Machine Tower
    [0xD55C0061]   = {"@Machine Tower: Foxy platforms ledge/"},
    [0xD55C0062]   = {"@Machine Tower: Knight fox meeting room/"},
    [0xD55C005B]   = {"@Machine Tower: Boneheaded argument wall kicks room/"},
    [0xD55C005A]   = {"@Machine Tower: Foxy fake wall/"},
    [0xD55C005F]  = {"@Machine Tower: Skelly-rang wall kicks room/"},
    [0xD55C005E]  = {"@Machine Tower: Fake Lilim wall/"},
    [0xD55C0063]  = {"@Machine Tower: Thunderous zone fake wall/"},
    [0xD55C005D]  = {"@Machine Tower: Thunderous zone lone Stone Armor room/"},
    [0xD55C005C] = {"@Machine Tower: Top lone Stone Armor room/"},
    [0xD55C0060] = {"@Machine Tower: Stone fox hallway/"},
    [0xD55C0064] = {"@Machine Tower: Pre-Iron Golem fake wall/"},
    [0xD55C00AB] = {"@Machine Tower: Behind Iron Golem/"},
    --Eternal Corridor
    [0xD55C0066]  = {"@Eternal Corridor: Midway fake wall/"},
    [0xD55C0065]  = {"@Eternal Corridor: Skelly-rang wall kicks room/"},
    [0xD55C0067]  = {"@Eternal Corridor: Skelly-rang fake wall/"},
    --Chapel Tower
    [0xD55C0068]   = {"@Chapel Tower: Flame Armor climb room/"},
    [0xD55C0069]   = {"@Chapel Tower: Lower chapel push crate room/"},
    [0xD55C0072]  = {"@Chapel Tower: Lower chapel fake wall/"},
    [0xD55C006B]  = {"@Chapel Tower: Beastly wall kicks room - Brain side/"},
    [0xD55C006C]  = {"@Chapel Tower: Beastly wall kicks room - Brawn side/"},
    [0xD55C006D]  = {"@Chapel Tower: Middle chapel fake wall/"},
    [0xD55C006E] = {"@Chapel Tower: Middle chapel push crate room/"},
    [0xD55C006F] = {"@Chapel Tower: Sharp mind climb room/"},
    [0xD55C0073] = {"@Chapel Tower: Upper chapel fake wall/"},
    [0xD55C0070] = {"@Chapel Tower: Upper chapel Marionette wall kicks/"},
    [0xD55C0074] = {"@Chapel Tower: Upper belfry fake wall/"},
 [0xD55C0071] = {"@Chapel Tower: Behind Adramelech iron maiden/"},
 [0xD55C009C] = {"@Chapel Tower: Outside Battle Arena - Upper/"},
 [0xD55C009B] = {"@Chapel Tower: Outside Battle Arena - Lower/"},
 --Underground Gallery
 [0xD55C0082] = {"@Underground Gallery: Conveyor platform ride/"},
 [0xD55C0083]  = {"@Underground Gallery: Conveyor upper push crate room/"},
 [0xD55C0081] = {"@Underground Gallery: Conveyor lower push crate room/"},
 [0xD55C0085] = {"@Underground Gallery: Harpy climb room - Lower/"},
 [0xD55C0084] = {"@Underground Gallery: Harpy climb room - Upper/"},
 [0xD55C0086]  = {"@Underground Gallery: Harpy mantis tackle hallway/"},
 [0xD55C0087] = {"@Underground Gallery: Handy bee hallway/"},
 [0xD55C0088]  = {"@Underground Gallery: Myconid fake wall/"},
 [0xD55C0089]  = {"@Underground Gallery: Crumble bridge fake wall/"},
 [0xD55C00AC]  = {"@Underground Gallery: Behind Dragon Zombies/"},
 --Underground Warehouse
 [0xD55C0075]   = {"@Underground Warehouse: Entrance push crate room/"},
 [0xD55C0076]  = {"@Underground Warehouse: Forever pushing room/"},
 [0xD55C0077]  = {"@Underground Warehouse: Crate-nudge fox room/"},
 [0xD55C007E]  = {"@Underground Warehouse: Crate-nudge fake wall/"},
 [0xD55C0078]  = {"@Underground Warehouse: Succubus shaft roc ledge/"},
 [0xD55C0079]  = {"@Underground Warehouse: Fake Lilith wall/"},
 [0xD55C007F] = {"@Underground Warehouse: Optional puzzle ceiling fake wall/"},
 [0xD55C007A] = {"@Underground Warehouse: Holy fox hideout - Left/"},
 [0xD55C007B] = {"@Underground Warehouse: Holy fox hideout - Right roc ledge/"},
 [0xD55C007C] = {"@Underground Warehouse: Forest Armor's domain fake wall/"},
 [0xD55C00AE] = {"@Underground Warehouse: Behind Death/"},
 [0xD55C0080]  = {"@Underground Warehouse: Behind Death fake wall/"},
 [0xD55C007D]  = {"@Underground Warehouse: Dryad expulsion chamber/"},
 --Underground Waterway
 [0xD55C0093]   = {"@Underground Waterway: Entrance fake wall/"},
 [0xD55C008B]  = {"@Underground Waterway: Before illusory wall/"},
 [0xD55C008A]  = {"@Underground Waterway: Beyond illusory wall/"},
 [0xD55C0094]  = {"@Underground Waterway: Ice Armor's domain fake wall/"},
 [0xD55C008C]  = {"@Underground Waterway: Brain freeze room/"},
 [0xD55C008D]  = {"@Underground Waterway: Middle lone Ice Armor room/"},
 [0xD55C0095]  = {"@Underground Waterway: Roc fake ceiling/"},
 [0xD55C008E]  = {"@Underground Waterway: Wicked Fishhead moat - Bottom/"},
 [0xD55C008F] = {"@Underground Waterway: Wicked Fishhead moat - Top/"},
 [0xD55C0090] = {"@Underground Waterway: Lizard-man turf - Bottom/"},
 [0xD55C0091] = {"@Underground Waterway: Lizard-man turf - Top/"},
 [0xD55C0092] = {"@Underground Waterway: Roc exit shaft/"},
 [0xD55C00AF] = {"@Underground Waterway: Behind Camilla/"},
 [0xD55C0096] = {"@Underground Waterway: Roc exit shaft fake wall/"},
 --Observation Tower
 [0xD55C009D] = {"@Observation Tower: Wind Armor rampart/"},
 [0xD55C00A4] = {"@Observation Tower: Legion plaza fake wall/"},
 [0xD55C009F] = {"@Observation Tower: Legion plaza Minotaur hallway/"},
 [0xD55C00A5] = {"@Observation Tower: Siren balcony fake wall/"},
 [0xD55C00A0] = {"@Observation Tower: Evil Pillar pit fake wall/"},
 [0xD55C00A2] = {"@Observation Tower: Alraune garden/"},
 [0xD55C00A6] = {"@Observation Tower: Dark Armor's domain fake wall/"},
 [0xD55C00A3] = {"@Observation Tower: Catoblepeas hallway/"},
 [0xD55C00A1] = {"@Observation Tower: Near warp room fake wall/"},
 [0xD55C00B0] = {"@Observation Tower: Behind Hugh/"},
 [0xD55C00A7] = {"@Ceremonial Room: Fake floor/"},
 [0xD55C00B2] = {"@Battle Arena: End reward"}, }